-- 由 scripts/geo/amap_terminal_link.py 生成（§10.2 第 5 问定案 ②）
-- 高德 driving 几何仅作「这条路存在」的几何来源，不作距离/时长口径；road_class='AMAP_LINK'。
-- 许可：这一段不是 ODbL，随公开仓库分发前请确认高德条款；摘除方式见下两行。
--   DELETE FROM t_road_segment WHERE road_class='AMAP_LINK';
--   DELETE FROM t_road_node WHERE node_code LIKE 'AM%';
INSERT INTO t_road_node (park_id,node_code,coord_x,coord_y,coord_lng,coord_lat,status,deleted) SELECT 1,'AMWL01',963.1906,1269.0287,121.1018280,31.9220630,'ACTIVE',0 FROM DUAL ON DUPLICATE KEY UPDATE coord_x=VALUES(coord_x),coord_y=VALUES(coord_y),coord_lng=VALUES(coord_lng),coord_lat=VALUES(coord_lat),status='ACTIVE',deleted=0;
INSERT INTO t_road_node (park_id,node_code,coord_x,coord_y,coord_lng,coord_lat,status,deleted) SELECT 1,'AMWL02',963.0767,1276.8177,121.1018220,31.9217150,'ACTIVE',0 FROM DUAL ON DUPLICATE KEY UPDATE coord_x=VALUES(coord_x),coord_y=VALUES(coord_y),coord_lng=VALUES(coord_lng),coord_lat=VALUES(coord_lat),status='ACTIVE',deleted=0;
INSERT INTO t_road_node (park_id,node_code,coord_x,coord_y,coord_lng,coord_lat,status,deleted) SELECT 1,'AMWL03',962.4688,1315.3600,121.1017900,31.9199930,'ACTIVE',0 FROM DUAL ON DUPLICATE KEY UPDATE coord_x=VALUES(coord_x),coord_y=VALUES(coord_y),coord_lng=VALUES(coord_lng),coord_lat=VALUES(coord_lat),status='ACTIVE',deleted=0;
INSERT INTO t_road_node (park_id,node_code,coord_x,coord_y,coord_lng,coord_lat,status,deleted) SELECT 1,'AMWL04',961.9560,1353.3203,121.1017630,31.9182970,'ACTIVE',0 FROM DUAL ON DUPLICATE KEY UPDATE coord_x=VALUES(coord_x),coord_y=VALUES(coord_y),coord_lng=VALUES(coord_lng),coord_lat=VALUES(coord_lat),status='ACTIVE',deleted=0;
INSERT INTO t_road_node (park_id,node_code,coord_x,coord_y,coord_lng,coord_lat,status,deleted) SELECT 1,'AMWL05',958.1192,1350.7911,121.1015610,31.9184100,'ACTIVE',0 FROM DUAL ON DUPLICATE KEY UPDATE coord_x=VALUES(coord_x),coord_y=VALUES(coord_y),coord_lng=VALUES(coord_lng),coord_lat=VALUES(coord_lat),status='ACTIVE',deleted=0;
INSERT INTO t_road_segment (park_id,from_node_code,to_node_code,direction,status,speed_limit_kmh,road_class,polyline_geojson,access_state,deleted) SELECT 1,'OSM0120','AMWL01','BIDIRECTIONAL','ACTIVE',20,'AMAP_LINK','{"type":"LineString","coordinates":[[121.1016525,31.9248827],[121.101828,31.922063]]}','DRIVABLE',0 FROM DUAL ON DUPLICATE KEY UPDATE direction=VALUES(direction),status=VALUES(status),speed_limit_kmh=VALUES(speed_limit_kmh),road_class=VALUES(road_class),polyline_geojson=VALUES(polyline_geojson),access_state=VALUES(access_state),deleted=0;
INSERT INTO t_road_segment (park_id,from_node_code,to_node_code,direction,status,speed_limit_kmh,road_class,polyline_geojson,access_state,deleted) SELECT 1,'AMWL01','AMWL02','BIDIRECTIONAL','ACTIVE',20,'AMAP_LINK','{"type":"LineString","coordinates":[[121.101828,31.922063],[121.101822,31.921715]]}','DRIVABLE',0 FROM DUAL ON DUPLICATE KEY UPDATE direction=VALUES(direction),status=VALUES(status),speed_limit_kmh=VALUES(speed_limit_kmh),road_class=VALUES(road_class),polyline_geojson=VALUES(polyline_geojson),access_state=VALUES(access_state),deleted=0;
INSERT INTO t_road_segment (park_id,from_node_code,to_node_code,direction,status,speed_limit_kmh,road_class,polyline_geojson,access_state,deleted) SELECT 1,'AMWL02','AMWL03','BIDIRECTIONAL','ACTIVE',20,'AMAP_LINK','{"type":"LineString","coordinates":[[121.101822,31.921715],[121.10179,31.919993]]}','DRIVABLE',0 FROM DUAL ON DUPLICATE KEY UPDATE direction=VALUES(direction),status=VALUES(status),speed_limit_kmh=VALUES(speed_limit_kmh),road_class=VALUES(road_class),polyline_geojson=VALUES(polyline_geojson),access_state=VALUES(access_state),deleted=0;
INSERT INTO t_road_segment (park_id,from_node_code,to_node_code,direction,status,speed_limit_kmh,road_class,polyline_geojson,access_state,deleted) SELECT 1,'AMWL03','AMWL04','BIDIRECTIONAL','ACTIVE',20,'AMAP_LINK','{"type":"LineString","coordinates":[[121.10179,31.919993],[121.101763,31.918297]]}','DRIVABLE',0 FROM DUAL ON DUPLICATE KEY UPDATE direction=VALUES(direction),status=VALUES(status),speed_limit_kmh=VALUES(speed_limit_kmh),road_class=VALUES(road_class),polyline_geojson=VALUES(polyline_geojson),access_state=VALUES(access_state),deleted=0;
INSERT INTO t_road_segment (park_id,from_node_code,to_node_code,direction,status,speed_limit_kmh,road_class,polyline_geojson,access_state,deleted) SELECT 1,'AMWL04','AMWL05','BIDIRECTIONAL','ACTIVE',20,'AMAP_LINK','{"type":"LineString","coordinates":[[121.101763,31.918297],[121.101561,31.91841]]}','DRIVABLE',0 FROM DUAL ON DUPLICATE KEY UPDATE direction=VALUES(direction),status=VALUES(status),speed_limit_kmh=VALUES(speed_limit_kmh),road_class=VALUES(road_class),polyline_geojson=VALUES(polyline_geojson),access_state=VALUES(access_state),deleted=0;
INSERT INTO t_road_node (park_id,node_code,coord_x,coord_y,coord_lng,coord_lat,status,deleted) SELECT 1,'AMCJ01',277.2338,1552.6121,121.0657140,31.9093930,'ACTIVE',0 FROM DUAL ON DUPLICATE KEY UPDATE coord_x=VALUES(coord_x),coord_y=VALUES(coord_y),coord_lng=VALUES(coord_lng),coord_lat=VALUES(coord_lat),status='ACTIVE',deleted=0;
INSERT INTO t_road_node (park_id,node_code,coord_x,coord_y,coord_lng,coord_lat,status,deleted) SELECT 1,'AMCJ02',281.2226,1552.6121,121.0659240,31.9093930,'ACTIVE',0 FROM DUAL ON DUPLICATE KEY UPDATE coord_x=VALUES(coord_x),coord_y=VALUES(coord_y),coord_lng=VALUES(coord_lng),coord_lat=VALUES(coord_lat),status='ACTIVE',deleted=0;
INSERT INTO t_road_node (park_id,node_code,coord_x,coord_y,coord_lng,coord_lat,status,deleted) SELECT 1,'AMCJ03',291.0996,1553.9550,121.0664440,31.9093330,'ACTIVE',0 FROM DUAL ON DUPLICATE KEY UPDATE coord_x=VALUES(coord_x),coord_y=VALUES(coord_y),coord_lng=VALUES(coord_lng),coord_lat=VALUES(coord_lat),status='ACTIVE',deleted=0;
INSERT INTO t_road_node (park_id,node_code,coord_x,coord_y,coord_lng,coord_lat,status,deleted) SELECT 1,'AMCJ04',290.3778,1545.4274,121.0664060,31.9097140,'ACTIVE',0 FROM DUAL ON DUPLICATE KEY UPDATE coord_x=VALUES(coord_x),coord_y=VALUES(coord_y),coord_lng=VALUES(coord_lng),coord_lat=VALUES(coord_lat),status='ACTIVE',deleted=0;
INSERT INTO t_road_node (park_id,node_code,coord_x,coord_y,coord_lng,coord_lat,status,deleted) SELECT 1,'AMCJ05',289.4661,1532.3337,121.0663580,31.9102990,'ACTIVE',0 FROM DUAL ON DUPLICATE KEY UPDATE coord_x=VALUES(coord_x),coord_y=VALUES(coord_y),coord_lng=VALUES(coord_lng),coord_lat=VALUES(coord_lat),status='ACTIVE',deleted=0;
INSERT INTO t_road_node (park_id,node_code,coord_x,coord_y,coord_lng,coord_lat,status,deleted) SELECT 1,'AMCJ06',288.7633,1521.5231,121.0663210,31.9107820,'ACTIVE',0 FROM DUAL ON DUPLICATE KEY UPDATE coord_x=VALUES(coord_x),coord_y=VALUES(coord_y),coord_lng=VALUES(coord_lng),coord_lat=VALUES(coord_lat),status='ACTIVE',deleted=0;
INSERT INTO t_road_node (park_id,node_code,coord_x,coord_y,coord_lng,coord_lat,status,deleted) SELECT 1,'AMCJ07',288.0415,1511.6749,121.0662830,31.9112220,'ACTIVE',0 FROM DUAL ON DUPLICATE KEY UPDATE coord_x=VALUES(coord_x),coord_y=VALUES(coord_y),coord_lng=VALUES(coord_lng),coord_lat=VALUES(coord_lat),status='ACTIVE',deleted=0;
INSERT INTO t_road_node (park_id,node_code,coord_x,coord_y,coord_lng,coord_lat,status,deleted) SELECT 1,'AMCJ08',287.2248,1498.9618,121.0662400,31.9117900,'ACTIVE',0 FROM DUAL ON DUPLICATE KEY UPDATE coord_x=VALUES(coord_x),coord_y=VALUES(coord_y),coord_lng=VALUES(coord_lng),coord_lat=VALUES(coord_lat),status='ACTIVE',deleted=0;
INSERT INTO t_road_node (park_id,node_code,coord_x,coord_y,coord_lng,coord_lat,status,deleted) SELECT 1,'AMCJ09',235.6745,1509.1681,121.0635260,31.9113340,'ACTIVE',0 FROM DUAL ON DUPLICATE KEY UPDATE coord_x=VALUES(coord_x),coord_y=VALUES(coord_y),coord_lng=VALUES(coord_lng),coord_lat=VALUES(coord_lat),status='ACTIVE',deleted=0;
INSERT INTO t_road_node (park_id,node_code,coord_x,coord_y,coord_lng,coord_lat,status,deleted) SELECT 1,'AMCJ10',234.1360,1495.5821,121.0634450,31.9119410,'ACTIVE',0 FROM DUAL ON DUPLICATE KEY UPDATE coord_x=VALUES(coord_x),coord_y=VALUES(coord_y),coord_lng=VALUES(coord_lng),coord_lat=VALUES(coord_lat),status='ACTIVE',deleted=0;
INSERT INTO t_road_node (park_id,node_code,coord_x,coord_y,coord_lng,coord_lat,status,deleted) SELECT 1,'AMCJ11',212.0077,1484.1895,121.0622800,31.9124500,'ACTIVE',0 FROM DUAL ON DUPLICATE KEY UPDATE coord_x=VALUES(coord_x),coord_y=VALUES(coord_y),coord_lng=VALUES(coord_lng),coord_lat=VALUES(coord_lat),status='ACTIVE',deleted=0;
INSERT INTO t_road_segment (park_id,from_node_code,to_node_code,direction,status,speed_limit_kmh,road_class,polyline_geojson,access_state,deleted) SELECT 1,'OSM0118','AMCJ01','BIDIRECTIONAL','ACTIVE',20,'AMAP_LINK','{"type":"LineString","coordinates":[[121.0620897,31.9089202],[121.065714,31.909393]]}','DRIVABLE',0 FROM DUAL ON DUPLICATE KEY UPDATE direction=VALUES(direction),status=VALUES(status),speed_limit_kmh=VALUES(speed_limit_kmh),road_class=VALUES(road_class),polyline_geojson=VALUES(polyline_geojson),access_state=VALUES(access_state),deleted=0;
INSERT INTO t_road_segment (park_id,from_node_code,to_node_code,direction,status,speed_limit_kmh,road_class,polyline_geojson,access_state,deleted) SELECT 1,'AMCJ01','AMCJ02','BIDIRECTIONAL','ACTIVE',20,'AMAP_LINK','{"type":"LineString","coordinates":[[121.065714,31.909393],[121.065924,31.909393]]}','DRIVABLE',0 FROM DUAL ON DUPLICATE KEY UPDATE direction=VALUES(direction),status=VALUES(status),speed_limit_kmh=VALUES(speed_limit_kmh),road_class=VALUES(road_class),polyline_geojson=VALUES(polyline_geojson),access_state=VALUES(access_state),deleted=0;
INSERT INTO t_road_segment (park_id,from_node_code,to_node_code,direction,status,speed_limit_kmh,road_class,polyline_geojson,access_state,deleted) SELECT 1,'AMCJ02','AMCJ03','BIDIRECTIONAL','ACTIVE',20,'AMAP_LINK','{"type":"LineString","coordinates":[[121.065924,31.909393],[121.066444,31.909333]]}','DRIVABLE',0 FROM DUAL ON DUPLICATE KEY UPDATE direction=VALUES(direction),status=VALUES(status),speed_limit_kmh=VALUES(speed_limit_kmh),road_class=VALUES(road_class),polyline_geojson=VALUES(polyline_geojson),access_state=VALUES(access_state),deleted=0;
INSERT INTO t_road_segment (park_id,from_node_code,to_node_code,direction,status,speed_limit_kmh,road_class,polyline_geojson,access_state,deleted) SELECT 1,'AMCJ03','AMCJ04','BIDIRECTIONAL','ACTIVE',20,'AMAP_LINK','{"type":"LineString","coordinates":[[121.066444,31.909333],[121.066406,31.909714]]}','DRIVABLE',0 FROM DUAL ON DUPLICATE KEY UPDATE direction=VALUES(direction),status=VALUES(status),speed_limit_kmh=VALUES(speed_limit_kmh),road_class=VALUES(road_class),polyline_geojson=VALUES(polyline_geojson),access_state=VALUES(access_state),deleted=0;
INSERT INTO t_road_segment (park_id,from_node_code,to_node_code,direction,status,speed_limit_kmh,road_class,polyline_geojson,access_state,deleted) SELECT 1,'AMCJ04','AMCJ05','BIDIRECTIONAL','ACTIVE',20,'AMAP_LINK','{"type":"LineString","coordinates":[[121.066406,31.909714],[121.066358,31.910299]]}','DRIVABLE',0 FROM DUAL ON DUPLICATE KEY UPDATE direction=VALUES(direction),status=VALUES(status),speed_limit_kmh=VALUES(speed_limit_kmh),road_class=VALUES(road_class),polyline_geojson=VALUES(polyline_geojson),access_state=VALUES(access_state),deleted=0;
INSERT INTO t_road_segment (park_id,from_node_code,to_node_code,direction,status,speed_limit_kmh,road_class,polyline_geojson,access_state,deleted) SELECT 1,'AMCJ05','AMCJ06','BIDIRECTIONAL','ACTIVE',20,'AMAP_LINK','{"type":"LineString","coordinates":[[121.066358,31.910299],[121.066321,31.910782]]}','DRIVABLE',0 FROM DUAL ON DUPLICATE KEY UPDATE direction=VALUES(direction),status=VALUES(status),speed_limit_kmh=VALUES(speed_limit_kmh),road_class=VALUES(road_class),polyline_geojson=VALUES(polyline_geojson),access_state=VALUES(access_state),deleted=0;
INSERT INTO t_road_segment (park_id,from_node_code,to_node_code,direction,status,speed_limit_kmh,road_class,polyline_geojson,access_state,deleted) SELECT 1,'AMCJ06','AMCJ07','BIDIRECTIONAL','ACTIVE',20,'AMAP_LINK','{"type":"LineString","coordinates":[[121.066321,31.910782],[121.066283,31.911222]]}','DRIVABLE',0 FROM DUAL ON DUPLICATE KEY UPDATE direction=VALUES(direction),status=VALUES(status),speed_limit_kmh=VALUES(speed_limit_kmh),road_class=VALUES(road_class),polyline_geojson=VALUES(polyline_geojson),access_state=VALUES(access_state),deleted=0;
INSERT INTO t_road_segment (park_id,from_node_code,to_node_code,direction,status,speed_limit_kmh,road_class,polyline_geojson,access_state,deleted) SELECT 1,'AMCJ07','AMCJ08','BIDIRECTIONAL','ACTIVE',20,'AMAP_LINK','{"type":"LineString","coordinates":[[121.066283,31.911222],[121.06624,31.91179]]}','DRIVABLE',0 FROM DUAL ON DUPLICATE KEY UPDATE direction=VALUES(direction),status=VALUES(status),speed_limit_kmh=VALUES(speed_limit_kmh),road_class=VALUES(road_class),polyline_geojson=VALUES(polyline_geojson),access_state=VALUES(access_state),deleted=0;
INSERT INTO t_road_segment (park_id,from_node_code,to_node_code,direction,status,speed_limit_kmh,road_class,polyline_geojson,access_state,deleted) SELECT 1,'AMCJ08','AMCJ09','BIDIRECTIONAL','ACTIVE',20,'AMAP_LINK','{"type":"LineString","coordinates":[[121.06624,31.91179],[121.063526,31.911334]]}','DRIVABLE',0 FROM DUAL ON DUPLICATE KEY UPDATE direction=VALUES(direction),status=VALUES(status),speed_limit_kmh=VALUES(speed_limit_kmh),road_class=VALUES(road_class),polyline_geojson=VALUES(polyline_geojson),access_state=VALUES(access_state),deleted=0;
INSERT INTO t_road_segment (park_id,from_node_code,to_node_code,direction,status,speed_limit_kmh,road_class,polyline_geojson,access_state,deleted) SELECT 1,'AMCJ09','AMCJ10','BIDIRECTIONAL','ACTIVE',20,'AMAP_LINK','{"type":"LineString","coordinates":[[121.063526,31.911334],[121.063445,31.911941]]}','DRIVABLE',0 FROM DUAL ON DUPLICATE KEY UPDATE direction=VALUES(direction),status=VALUES(status),speed_limit_kmh=VALUES(speed_limit_kmh),road_class=VALUES(road_class),polyline_geojson=VALUES(polyline_geojson),access_state=VALUES(access_state),deleted=0;
INSERT INTO t_road_segment (park_id,from_node_code,to_node_code,direction,status,speed_limit_kmh,road_class,polyline_geojson,access_state,deleted) SELECT 1,'AMCJ10','AMCJ11','BIDIRECTIONAL','ACTIVE',20,'AMAP_LINK','{"type":"LineString","coordinates":[[121.063445,31.911941],[121.06228,31.91245]]}','DRIVABLE',0 FROM DUAL ON DUPLICATE KEY UPDATE direction=VALUES(direction),status=VALUES(status),speed_limit_kmh=VALUES(speed_limit_kmh),road_class=VALUES(road_class),polyline_geojson=VALUES(polyline_geojson),access_state=VALUES(access_state),deleted=0;
