-- 基地待命车位 P01..P20（空闲车"回待命区"的落点）
--
-- 为什么要这一片：仿真器给空闲车挑待命点的顺序是
--   ① `ZJF-IDLE-01` 站点（设施 v2 把它连同所有 GENERAL 站点一起置了 INACTIVE ⇒ 接口不返回 ⇒ 找不到）
--   ② 回退到 `application.yml` 的 `parking-spots P1..P6`，那是**老示意图的像素坐标**
--      （x=80..200 / y=700..740，对现役 1600×1854 画布没有意义）
-- 结果 20 台车被分到 6 个凭空点上，实测有 3 台因此落在服务围栏外、且三台叠在同一个坐标。
--
-- 现在的口径：待命点 = `t_parking_slot` 里 `slot_type='STANDBY'` 的真车位，
-- 空闲车通过 `ParkingFacilityService.reserveStandbySlot()` 原子占位（FREE→RESERVED），
-- 派单/离开时由既有生命周期 `releaseByVehicle()/releaseReservation()` 释放。
--
-- 选点规则（可复现）：以路网节点 OSM0017（现役基地锚点）为圆心，取
-- **在最大强连通分量里（`t_road_node_component.is_largest=1`）的 ACTIVE 节点**按距离升序前 20 个；
-- `coord_x/coord_y` 与 `coord_lng/coord_lat` **成对取自同一个节点**，
-- 不在脚本里重算 GCJ↔像素互转（那份实现只在 `ParkGeoTransformService` 一处，重算必漂）。
--
-- ⚠ 这是地理内容，走 seed 不走迁移；灌 seed 前必须先停后端（否则仿真器每 tick 在写车位状态，
--   灌完立刻被覆盖）。P1..P6 原有的 OCCUPIED/occupied_vehicle_id 不在本文件的更新列里，不会被解开。
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `facing_direction`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'P1', '基地待命位 01', 'STANDBY', NULL, 'OSM0017', 'OSM0017', 0, 550.1236, 406.6709, 121.0800810, 31.9605916, 'FREE', NULL, 1, '就近路网节点 OSM0017（距基地 0 m）', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `facing_direction`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'P2', '基地待命位 02', 'STANDBY', NULL, 'OSM0267', 'OSM0267', 0, 536.9986, 405.8584, 121.0793900, 31.9606279, 'FREE', NULL, 2, '就近路网节点 OSM0267（距基地 66 m）', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `facing_direction`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'P3', '基地待命位 03', 'STANDBY', NULL, 'OSMS0072', 'OSMS0072', 0, 518.0008, 376.7705, 121.0783898, 31.9619275, 'FREE', NULL, 3, '就近路网节点 OSMS0072（距基地 218 m）', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `facing_direction`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'P4', '基地待命位 04', 'STANDBY', NULL, 'OSM0265', 'OSM0265', 0, 509.6754, 424.7961, 121.0779515, 31.9597818, 'FREE', NULL, 4, '就近路网节点 OSM0265（距基地 221 m）', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `facing_direction`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'P5', '基地待命位 05', 'STANDBY', NULL, 'OSM0259', 'OSM0259', 0, 541.5287, 454.1191, 121.0796285, 31.9584717, 'FREE', NULL, 5, '就近路网节点 OSM0259（距基地 238 m）', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `facing_direction`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'P6', '基地待命位 06', 'STANDBY', NULL, 'OSM0018', 'OSM0018', 0, 602.7281, 406.3173, 121.0828505, 31.9606074, 'FREE', NULL, 6, '就近路网节点 OSM0018（距基地 263 m）', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `facing_direction`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'P7', '基地待命位 07', 'STANDBY', NULL, 'OSM0256', 'OSM0256', 0, 557.0603, 461.9148, 121.0804462, 31.9581234, 'FREE', NULL, 7, '就近路网节点 OSM0256（距基地 275 m）', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `facing_direction`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'P8', '基地待命位 08', 'STANDBY', NULL, 'OSM0044', 'OSM0044', 0, 568.2821, 352.0514, 121.0810370, 31.9630319, 'FREE', NULL, 8, '就近路网节点 OSM0044（距基地 285 m）', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `facing_direction`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'P9', '基地待命位 09', 'STANDBY', NULL, 'OSM0010', 'OSM0010', 0, 541.5249, 347.9734, 121.0796283, 31.9632141, 'FREE', NULL, 9, '就近路网节点 OSM0010（距基地 293 m）', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `facing_direction`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'P10', '基地待命位 10', 'STANDBY', NULL, 'OSM0011', 'OSM0011', 0, 548.6307, 347.0087, 121.0800024, 31.9632572, 'FREE', NULL, 10, '就近路网节点 OSM0011（距基地 295 m）', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `facing_direction`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'P11', '基地待命位 11', 'STANDBY', NULL, 'OSM0258', 'OSM0258', 0, 512.1238, 456.0373, 121.0780804, 31.9583860, 'FREE', NULL, 11, '就近路网节点 OSM0258（距基地 309 m）', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `facing_direction`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'P12', '基地待命位 12', 'STANDBY', NULL, 'OSM0009', 'OSM0009', 0, 560.5533, 340.1217, 121.0806301, 31.9635649, 'FREE', NULL, 12, '就近路网节点 OSM0009（距基地 333 m）', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `facing_direction`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'P13', '基地待命位 13', 'STANDBY', NULL, 'OSM0260', 'OSM0260', 0, 608.0161, 446.3054, 121.0831289, 31.9588208, 'FREE', NULL, 13, '就近路网节点 OSM0260（距基地 350 m）', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `facing_direction`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'P14', '基地待命位 14', 'STANDBY', NULL, 'OSM0264', 'OSM0264', 0, 474.2076, 427.6565, 121.0760842, 31.9596540, 'FREE', NULL, 14, '就近路网节点 OSM0264（距基地 394 m）', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `facing_direction`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'P15', '基地待命位 15', 'STANDBY', NULL, 'OSM0093', 'OSM0093', 0, 477.4841, 375.9311, 121.0762567, 31.9619650, 'FREE', NULL, 15, '就近路网节点 OSM0093（距基地 394 m）', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `facing_direction`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'P16', '基地待命位 16', 'STANDBY', NULL, 'OSM0008', 'OSM0008', 0, 538.4004, 325.4680, 121.0794638, 31.9642196, 'FREE', NULL, 16, '就近路网节点 OSM0008（距基地 405 m）', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `facing_direction`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'P17', '基地待命位 17', 'STANDBY', NULL, 'OSMS0026', 'OSMS0026', 0, 619.3096, 356.3986, 121.0837235, 31.9628377, 'FREE', NULL, 17, '就近路网节点 OSMS0026（距基地 426 m）', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `facing_direction`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'P18', '基地待命位 18', 'STANDBY', NULL, 'OSMS0211', 'OSMS0211', 0, 618.6889, 458.7582, 121.0836908, 31.9582644, 'FREE', NULL, 18, '就近路网节点 OSMS0211（距基地 429 m）', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `facing_direction`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'P19', '基地待命位 19', 'STANDBY', NULL, 'OSM0303', 'OSM0303', 0, 570.3012, 310.7271, 121.0811433, 31.9648782, 'FREE', NULL, 19, '就近路网节点 OSM0303（距基地 485 m）', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `facing_direction`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'P20', '基地待命位 20', 'STANDBY', NULL, 'OSM0307', 'OSM0307', 0, 572.0106, 305.7806, 121.0812333, 31.9650992, 'FREE', NULL, 20, '就近路网节点 OSM0307（距基地 510 m）', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
