-- 卫星补能点 E1..E2：可停车 + 可充电，其中 1 号点配 30 s 快速换电柜
--
-- 为什么要这一片：现役补能容量与车队规模差得太远 —— 真柜只有 1 台（地图上那 35 个 FSD-SWAP-*
--   只是站点行，没有柜记录，所以 t_battery_swap_session 至今 0 行），充电桩 6 个且全忙，
--   而车队 35 台。结果是空闲车全体沉到 `reserve-soc-floor` 以下、在图上表现成"一堆故障车"。
-- 拓扑（本人 2026-09-25 裁定）：母港保留统一停车位（见 zjf_standby_slots.sql），
--   另在服务范围内选 2 个点（西南 E1 / 东北 E2），每点 8 个"车位+桩"，E1 配 30 s 换电柜（8 位）。
--   容量按**点位**算而不是按车位算：一个点同时能补 8 台；"一位一车"的排他性只留在桩这一层
--   （`uk_parking_slot`），所以点少不等于容量小。
--
-- 选点规则（可复现）：
--   ① 两个方向探针（西南 121.0620/31.9120、东北 121.1180/31.9650）各取"最近的、服务围栏内、
--      在最大强连通分量里的 ACTIVE 路网节点，且离基地 OSM0017 ≥ 1500 m"作为站点；
--   ② 每站点的 8 个车位 = 离该站点最近的 8 个同类节点（像素与经纬度成对取自同一节点，
--      不在脚本里重算 GCJ↔像素互转）；③ 换电柜只放在离基地最远的 E1。
--
-- 站点：E1=AMCJ11(5585m)、E2=OSM0301(3613m)
-- 换电点：E1
-- ⚠ 地理内容走 seed，不自动导入；灌之前必须停后端（仿真器每 tick 在写车位/桩位状态）。

INSERT INTO t_station (`park_id`, `station_code`, `station_name`, `station_type`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `area`, `status`, `sort_order`, `anchor_node_code`, `service_direction`, `station_confidence`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'FSD-CHG-11', '卫星补能点 1（AMCJ11）', 'CHARGING_STATION', 212.0077, 1484.1895, 121.0622800, 31.9124500, 'E1', 'ACTIVE', 1, 'AMCJ11', 'BIDIRECTIONAL', 'A', '可停车+可充电；配 30 s 快速换电柜，离基地 5585 m', 0 FROM DUAL ON DUPLICATE KEY UPDATE `station_name`=VALUES(`station_name`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `status`=VALUES(`status`), `anchor_node_code`=VALUES(`anchor_node_code`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_station (`park_id`, `station_code`, `station_name`, `station_type`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `area`, `status`, `sort_order`, `anchor_node_code`, `service_direction`, `station_confidence`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'FSD-CHG-12', '卫星补能点 2（OSM0301）', 'CHARGING_STATION', 1267.0504, 317.4664, 121.1178255, 31.9645771, 'E2', 'ACTIVE', 2, 'OSM0301', 'BIDIRECTIONAL', 'A', '可停车+可充电，离基地 3613 m', 0 FROM DUAL ON DUPLICATE KEY UPDATE `station_name`=VALUES(`station_name`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `status`=VALUES(`status`), `anchor_node_code`=VALUES(`anchor_node_code`), `remark`=VALUES(`remark`), `deleted`=0;

INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'E1B1', '补能点 E1 车位 1', 'CHARGING_ONLY', 'AMCJ11', 'AMCJ11', 0, 212.0077, 1484.1895, 121.0622800, 31.9124500, 'FREE', NULL, 11, '卫星补能点车位（停车+充电），节点 AMCJ11', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'E1B2', '补能点 E1 车位 2', 'CHARGING_ONLY', 'AMCJ10', 'AMCJ10', 0, 234.1360, 1495.5821, 121.0634450, 31.9119410, 'FREE', NULL, 12, '卫星补能点车位（停车+充电），节点 AMCJ10', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'E1B3', '补能点 E1 车位 3', 'CHARGING_ONLY', 'AMCJ09', 'AMCJ09', 0, 235.6745, 1509.1681, 121.0635260, 31.9113340, 'FREE', NULL, 13, '卫星补能点车位（停车+充电），节点 AMCJ09', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'E1B4', '补能点 E1 车位 4', 'CHARGING_ONLY', 'OSMS0116', 'OSMS0116', 0, 282.1004, 1479.1190, 121.0659702, 31.9126765, 'FREE', NULL, 14, '卫星补能点车位（停车+充电），节点 OSMS0116', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'E1B5', '补能点 E1 车位 5', 'CHARGING_ONLY', 'AMCJ08', 'AMCJ08', 0, 287.2248, 1498.9618, 121.0662400, 31.9117900, 'FREE', NULL, 15, '卫星补能点车位（停车+充电），节点 AMCJ08', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'E1B6', '补能点 E1 车位 6', 'CHARGING_ONLY', 'OSM0118', 'OSM0118', 0, 208.3931, 1563.1944, 121.0620897, 31.9089202, 'FREE', NULL, 16, '卫星补能点车位（停车+充电），节点 OSM0118', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'E1B7', '补能点 E1 车位 7', 'CHARGING_ONLY', 'AMCJ07', 'AMCJ07', 0, 288.0415, 1511.6749, 121.0662830, 31.9112220, 'FREE', NULL, 17, '卫星补能点车位（停车+充电），节点 AMCJ07', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'E1B8', '补能点 E1 车位 8', 'CHARGING_ONLY', 'AMCJ06', 'AMCJ06', 0, 288.7633, 1521.5231, 121.0663210, 31.9107820, 'FREE', NULL, 18, '卫星补能点车位（停车+充电），节点 AMCJ06', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'E2B1', '补能点 E2 车位 1', 'CHARGING_ONLY', 'OSM0301', 'OSM0301', 0, 1267.0504, 317.4664, 121.1178255, 31.9645771, 'FREE', NULL, 21, '卫星补能点车位（停车+充电），节点 OSM0301', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'E2B2', '补能点 E2 车位 2', 'CHARGING_ONLY', 'OSM0095', 'OSM0095', 0, 1254.4003, 318.4803, 121.1171595, 31.9645318, 'FREE', NULL, 22, '卫星补能点车位（停车+充电），节点 OSM0095', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'E2B3', '补能点 E2 车位 3', 'CHARGING_ONLY', 'OSM0324', 'OSM0324', 0, 1254.4801, 291.6104, 121.1171637, 31.9657323, 'FREE', NULL, 23, '卫星补能点车位（停车+充电），节点 OSM0324', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'E2B4', '补能点 E2 车位 4', 'CHARGING_ONLY', 'OSM0283', 'OSM0283', 0, 1255.8078, 351.7739, 121.1172336, 31.9630443, 'FREE', NULL, 24, '卫星补能点车位（停车+充电），节点 OSM0283', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'E2B5', '补能点 E2 车位 5', 'CHARGING_ONLY', 'OSM0335', 'OSM0335', 0, 1265.6335, 273.7717, 121.1177509, 31.9665293, 'FREE', NULL, 25, '卫星补能点车位（停车+充电），节点 OSM0335', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'E2B6', '补能点 E2 车位 6', 'CHARGING_ONLY', 'OSM0102', 'OSM0102', 0, 1254.5371, 272.9928, 121.1171667, 31.9665641, 'FREE', NULL, 26, '卫星补能点车位（停车+充电），节点 OSM0102', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'E2B7', '补能点 E2 车位 7', 'CHARGING_ONLY', 'OSMS0216', 'OSMS0216', 0, 1268.7485, 368.3856, 121.1179149, 31.9623021, 'FREE', NULL, 27, '卫星补能点车位（停车+充电），节点 OSMS0216', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_parking_slot (`park_id`, `slot_code`, `slot_name`, `slot_type`, `entry_node_code`, `exit_node_code`, `blocking_main_road`, `coord_x`, `coord_y`, `coord_lng`, `coord_lat`, `status`, `occupied_vehicle_id`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'E2B8', '补能点 E2 车位 8', 'CHARGING_ONLY', 'OSMS0225', 'OSMS0225', 0, 1318.5164, 324.7584, 121.1205351, 31.9642513, 'FREE', NULL, 28, '卫星补能点车位（停车+充电），节点 OSMS0225', 0 FROM DUAL ON DUPLICATE KEY UPDATE `slot_name`=VALUES(`slot_name`), `slot_type`=VALUES(`slot_type`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `coord_lng`=VALUES(`coord_lng`), `coord_lat`=VALUES(`coord_lat`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;

INSERT INTO t_charging_pile (`park_id`, `pile_code`, `pile_name`, `parking_slot_id`, `status`, `max_power_kw`, `entry_node_code`, `exit_node_code`, `plug_type`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'PILE-E1B1', '补能点 E1 桩 1', (SELECT id FROM t_parking_slot WHERE park_id=(SELECT id FROM t_park WHERE park_code='DEFAULT') AND slot_code='E1B1' AND deleted=0), 'FREE', 60.00, 'AMCJ11', 'AMCJ11', 'GB-T', 11, '与车位 E1B1 一对一绑定', 0 FROM DUAL ON DUPLICATE KEY UPDATE `pile_name`=VALUES(`pile_name`), `parking_slot_id`=VALUES(`parking_slot_id`), `max_power_kw`=VALUES(`max_power_kw`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_charging_pile (`park_id`, `pile_code`, `pile_name`, `parking_slot_id`, `status`, `max_power_kw`, `entry_node_code`, `exit_node_code`, `plug_type`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'PILE-E1B2', '补能点 E1 桩 2', (SELECT id FROM t_parking_slot WHERE park_id=(SELECT id FROM t_park WHERE park_code='DEFAULT') AND slot_code='E1B2' AND deleted=0), 'FREE', 60.00, 'AMCJ10', 'AMCJ10', 'GB-T', 12, '与车位 E1B2 一对一绑定', 0 FROM DUAL ON DUPLICATE KEY UPDATE `pile_name`=VALUES(`pile_name`), `parking_slot_id`=VALUES(`parking_slot_id`), `max_power_kw`=VALUES(`max_power_kw`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_charging_pile (`park_id`, `pile_code`, `pile_name`, `parking_slot_id`, `status`, `max_power_kw`, `entry_node_code`, `exit_node_code`, `plug_type`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'PILE-E1B3', '补能点 E1 桩 3', (SELECT id FROM t_parking_slot WHERE park_id=(SELECT id FROM t_park WHERE park_code='DEFAULT') AND slot_code='E1B3' AND deleted=0), 'FREE', 60.00, 'AMCJ09', 'AMCJ09', 'GB-T', 13, '与车位 E1B3 一对一绑定', 0 FROM DUAL ON DUPLICATE KEY UPDATE `pile_name`=VALUES(`pile_name`), `parking_slot_id`=VALUES(`parking_slot_id`), `max_power_kw`=VALUES(`max_power_kw`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_charging_pile (`park_id`, `pile_code`, `pile_name`, `parking_slot_id`, `status`, `max_power_kw`, `entry_node_code`, `exit_node_code`, `plug_type`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'PILE-E1B4', '补能点 E1 桩 4', (SELECT id FROM t_parking_slot WHERE park_id=(SELECT id FROM t_park WHERE park_code='DEFAULT') AND slot_code='E1B4' AND deleted=0), 'FREE', 60.00, 'OSMS0116', 'OSMS0116', 'GB-T', 14, '与车位 E1B4 一对一绑定', 0 FROM DUAL ON DUPLICATE KEY UPDATE `pile_name`=VALUES(`pile_name`), `parking_slot_id`=VALUES(`parking_slot_id`), `max_power_kw`=VALUES(`max_power_kw`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_charging_pile (`park_id`, `pile_code`, `pile_name`, `parking_slot_id`, `status`, `max_power_kw`, `entry_node_code`, `exit_node_code`, `plug_type`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'PILE-E1B5', '补能点 E1 桩 5', (SELECT id FROM t_parking_slot WHERE park_id=(SELECT id FROM t_park WHERE park_code='DEFAULT') AND slot_code='E1B5' AND deleted=0), 'FREE', 60.00, 'AMCJ08', 'AMCJ08', 'GB-T', 15, '与车位 E1B5 一对一绑定', 0 FROM DUAL ON DUPLICATE KEY UPDATE `pile_name`=VALUES(`pile_name`), `parking_slot_id`=VALUES(`parking_slot_id`), `max_power_kw`=VALUES(`max_power_kw`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_charging_pile (`park_id`, `pile_code`, `pile_name`, `parking_slot_id`, `status`, `max_power_kw`, `entry_node_code`, `exit_node_code`, `plug_type`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'PILE-E1B6', '补能点 E1 桩 6', (SELECT id FROM t_parking_slot WHERE park_id=(SELECT id FROM t_park WHERE park_code='DEFAULT') AND slot_code='E1B6' AND deleted=0), 'FREE', 60.00, 'OSM0118', 'OSM0118', 'GB-T', 16, '与车位 E1B6 一对一绑定', 0 FROM DUAL ON DUPLICATE KEY UPDATE `pile_name`=VALUES(`pile_name`), `parking_slot_id`=VALUES(`parking_slot_id`), `max_power_kw`=VALUES(`max_power_kw`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_charging_pile (`park_id`, `pile_code`, `pile_name`, `parking_slot_id`, `status`, `max_power_kw`, `entry_node_code`, `exit_node_code`, `plug_type`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'PILE-E1B7', '补能点 E1 桩 7', (SELECT id FROM t_parking_slot WHERE park_id=(SELECT id FROM t_park WHERE park_code='DEFAULT') AND slot_code='E1B7' AND deleted=0), 'FREE', 60.00, 'AMCJ07', 'AMCJ07', 'GB-T', 17, '与车位 E1B7 一对一绑定', 0 FROM DUAL ON DUPLICATE KEY UPDATE `pile_name`=VALUES(`pile_name`), `parking_slot_id`=VALUES(`parking_slot_id`), `max_power_kw`=VALUES(`max_power_kw`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_charging_pile (`park_id`, `pile_code`, `pile_name`, `parking_slot_id`, `status`, `max_power_kw`, `entry_node_code`, `exit_node_code`, `plug_type`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'PILE-E1B8', '补能点 E1 桩 8', (SELECT id FROM t_parking_slot WHERE park_id=(SELECT id FROM t_park WHERE park_code='DEFAULT') AND slot_code='E1B8' AND deleted=0), 'FREE', 60.00, 'AMCJ06', 'AMCJ06', 'GB-T', 18, '与车位 E1B8 一对一绑定', 0 FROM DUAL ON DUPLICATE KEY UPDATE `pile_name`=VALUES(`pile_name`), `parking_slot_id`=VALUES(`parking_slot_id`), `max_power_kw`=VALUES(`max_power_kw`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_charging_pile (`park_id`, `pile_code`, `pile_name`, `parking_slot_id`, `status`, `max_power_kw`, `entry_node_code`, `exit_node_code`, `plug_type`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'PILE-E2B1', '补能点 E2 桩 1', (SELECT id FROM t_parking_slot WHERE park_id=(SELECT id FROM t_park WHERE park_code='DEFAULT') AND slot_code='E2B1' AND deleted=0), 'FREE', 60.00, 'OSM0301', 'OSM0301', 'GB-T', 21, '与车位 E2B1 一对一绑定', 0 FROM DUAL ON DUPLICATE KEY UPDATE `pile_name`=VALUES(`pile_name`), `parking_slot_id`=VALUES(`parking_slot_id`), `max_power_kw`=VALUES(`max_power_kw`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_charging_pile (`park_id`, `pile_code`, `pile_name`, `parking_slot_id`, `status`, `max_power_kw`, `entry_node_code`, `exit_node_code`, `plug_type`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'PILE-E2B2', '补能点 E2 桩 2', (SELECT id FROM t_parking_slot WHERE park_id=(SELECT id FROM t_park WHERE park_code='DEFAULT') AND slot_code='E2B2' AND deleted=0), 'FREE', 60.00, 'OSM0095', 'OSM0095', 'GB-T', 22, '与车位 E2B2 一对一绑定', 0 FROM DUAL ON DUPLICATE KEY UPDATE `pile_name`=VALUES(`pile_name`), `parking_slot_id`=VALUES(`parking_slot_id`), `max_power_kw`=VALUES(`max_power_kw`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_charging_pile (`park_id`, `pile_code`, `pile_name`, `parking_slot_id`, `status`, `max_power_kw`, `entry_node_code`, `exit_node_code`, `plug_type`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'PILE-E2B3', '补能点 E2 桩 3', (SELECT id FROM t_parking_slot WHERE park_id=(SELECT id FROM t_park WHERE park_code='DEFAULT') AND slot_code='E2B3' AND deleted=0), 'FREE', 60.00, 'OSM0324', 'OSM0324', 'GB-T', 23, '与车位 E2B3 一对一绑定', 0 FROM DUAL ON DUPLICATE KEY UPDATE `pile_name`=VALUES(`pile_name`), `parking_slot_id`=VALUES(`parking_slot_id`), `max_power_kw`=VALUES(`max_power_kw`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_charging_pile (`park_id`, `pile_code`, `pile_name`, `parking_slot_id`, `status`, `max_power_kw`, `entry_node_code`, `exit_node_code`, `plug_type`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'PILE-E2B4', '补能点 E2 桩 4', (SELECT id FROM t_parking_slot WHERE park_id=(SELECT id FROM t_park WHERE park_code='DEFAULT') AND slot_code='E2B4' AND deleted=0), 'FREE', 60.00, 'OSM0283', 'OSM0283', 'GB-T', 24, '与车位 E2B4 一对一绑定', 0 FROM DUAL ON DUPLICATE KEY UPDATE `pile_name`=VALUES(`pile_name`), `parking_slot_id`=VALUES(`parking_slot_id`), `max_power_kw`=VALUES(`max_power_kw`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_charging_pile (`park_id`, `pile_code`, `pile_name`, `parking_slot_id`, `status`, `max_power_kw`, `entry_node_code`, `exit_node_code`, `plug_type`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'PILE-E2B5', '补能点 E2 桩 5', (SELECT id FROM t_parking_slot WHERE park_id=(SELECT id FROM t_park WHERE park_code='DEFAULT') AND slot_code='E2B5' AND deleted=0), 'FREE', 60.00, 'OSM0335', 'OSM0335', 'GB-T', 25, '与车位 E2B5 一对一绑定', 0 FROM DUAL ON DUPLICATE KEY UPDATE `pile_name`=VALUES(`pile_name`), `parking_slot_id`=VALUES(`parking_slot_id`), `max_power_kw`=VALUES(`max_power_kw`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_charging_pile (`park_id`, `pile_code`, `pile_name`, `parking_slot_id`, `status`, `max_power_kw`, `entry_node_code`, `exit_node_code`, `plug_type`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'PILE-E2B6', '补能点 E2 桩 6', (SELECT id FROM t_parking_slot WHERE park_id=(SELECT id FROM t_park WHERE park_code='DEFAULT') AND slot_code='E2B6' AND deleted=0), 'FREE', 60.00, 'OSM0102', 'OSM0102', 'GB-T', 26, '与车位 E2B6 一对一绑定', 0 FROM DUAL ON DUPLICATE KEY UPDATE `pile_name`=VALUES(`pile_name`), `parking_slot_id`=VALUES(`parking_slot_id`), `max_power_kw`=VALUES(`max_power_kw`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_charging_pile (`park_id`, `pile_code`, `pile_name`, `parking_slot_id`, `status`, `max_power_kw`, `entry_node_code`, `exit_node_code`, `plug_type`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'PILE-E2B7', '补能点 E2 桩 7', (SELECT id FROM t_parking_slot WHERE park_id=(SELECT id FROM t_park WHERE park_code='DEFAULT') AND slot_code='E2B7' AND deleted=0), 'FREE', 60.00, 'OSMS0216', 'OSMS0216', 'GB-T', 27, '与车位 E2B7 一对一绑定', 0 FROM DUAL ON DUPLICATE KEY UPDATE `pile_name`=VALUES(`pile_name`), `parking_slot_id`=VALUES(`parking_slot_id`), `max_power_kw`=VALUES(`max_power_kw`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;
INSERT INTO t_charging_pile (`park_id`, `pile_code`, `pile_name`, `parking_slot_id`, `status`, `max_power_kw`, `entry_node_code`, `exit_node_code`, `plug_type`, `sort_order`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'PILE-E2B8', '补能点 E2 桩 8', (SELECT id FROM t_parking_slot WHERE park_id=(SELECT id FROM t_park WHERE park_code='DEFAULT') AND slot_code='E2B8' AND deleted=0), 'FREE', 60.00, 'OSMS0225', 'OSMS0225', 'GB-T', 28, '与车位 E2B8 一对一绑定', 0 FROM DUAL ON DUPLICATE KEY UPDATE `pile_name`=VALUES(`pile_name`), `parking_slot_id`=VALUES(`parking_slot_id`), `max_power_kw`=VALUES(`max_power_kw`), `entry_node_code`=VALUES(`entry_node_code`), `exit_node_code`=VALUES(`exit_node_code`), `sort_order`=VALUES(`sort_order`), `remark`=VALUES(`remark`), `deleted`=0;

INSERT INTO t_battery_swap_cabinet (`park_id`, `cabinet_code`, `cabinet_name`, `coord_x`, `coord_y`, `slot_count`, `status`, `remark`, `deleted`) SELECT (SELECT id FROM t_park WHERE park_code='DEFAULT'), 'SWAP-E1', '快速换电柜 · 补能点 E1', 212.0077, 1484.1895, 8, 'ACTIVE', '30 s 快速换电；站点节点 AMCJ11，离基地 5585 m', 0 FROM DUAL ON DUPLICATE KEY UPDATE `cabinet_name`=VALUES(`cabinet_name`), `coord_x`=VALUES(`coord_x`), `coord_y`=VALUES(`coord_y`), `slot_count`=VALUES(`slot_count`), `status`=VALUES(`status`), `remark`=VALUES(`remark`), `deleted`=0;
