export enum OrderStatus {
  CREATED = 'CREATED',
  WAITING_DISPATCH = 'WAITING_DISPATCH',
  DISPATCHED = 'DISPATCHED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}

export enum TaskStatus {
  PENDING = 'PENDING',
  ASSIGNING = 'ASSIGNING',
  ASSIGNED = 'ASSIGNED',
  EXECUTING = 'EXECUTING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  MANUAL_PENDING = 'MANUAL_PENDING',
}

export enum OnlineStatus {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
}

export enum DispatchStatus {
  IDLE = 'IDLE',
  BUSY = 'BUSY',
  UNAVAILABLE = 'UNAVAILABLE',
}

export enum ExceptionType {
  TASK_EXECUTE_FAILED = 'TASK_EXECUTE_FAILED',
  VEHICLE_OFFLINE = 'VEHICLE_OFFLINE',
  EXECUTE_TIMEOUT = 'EXECUTE_TIMEOUT',
  STATUS_REPORT_ERROR = 'STATUS_REPORT_ERROR',
}

export enum ExceptionStatus {
  OPEN = 'OPEN',
  RESOLVED = 'RESOLVED',
}
